// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTUser = "t_user"

// TUser mapped from table <t_user>
type TUser struct {
	ID       int64  `gorm:"column:id;type:bigint;primaryKey" json:"id"`
	Username string `gorm:"column:username;type:character varying(255);not null" json:"username"`
}

// TableName TUser's table name
func (*TUser) TableName() string {
	return TableNameTUser
}
