openapi: 3.0.0
info:
  version: 1.0.0
  title: event management app
  license:
    name: MIT
servers:
  - url: 'http://petstore.swagger.io/v1'
paths:
  /:
    get:
      summary: Health Check
      operationId: echo
      tags:
        - echo
      responses:
        '200':
          description: 成功レスポンス
          content:
            application/json:
              schema:
                type: object
                required:
                  - code
                properties:
                  code:
                    type: integer
